### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by lubien** [lubien/ufpa-advanced-databases-2018-assignment-01#1]
As @gustavopinto website is a little tricky over the points of the assignment I'll list here so I can tackle all.

## Implementation
- [x] Code should be on GitHub (kek)
- [x] Implemented binary database
- [x] Used a relational DBMS
- [x] 3 self made queries using the other 3 unused fields alongside `country`

## Report
- [x] Machine setup
- [x] Tables/charts of results
- [x] DBMS description
- [x] Implemented algorithms
- [x] Discussion over results
- [x] Measure storage usage
- [x] Measure time (first and mean of 3)

## Presentation
- [x] Machine setup
- [x] DBMS description
- [x] Considered DBMS
- [x] Tables/charts of results
- [x] SQL queries
- [x] Measure storage usage
- [x] Measure time (first and mean of 3)

TODO: put this on README
